### ISSUE TITLE
整数の閉区間 TODOリスト

### ISSUE THREAD

**Issue by progfay** [progfay/javascript-jest#1]
## 課題

> 整数閉区間を示すクラス（あるいは構造体）をつくりたい。整数閉区間オブジェクトは下端点と上端点を持ち、文字列表現も返せる（例: 下端点 3, 上端点 8 の整数閉区間の文字列表記は "[3,8]"）。ただし、上端点より下端点が大きい閉区間を作ることはできない。整数の閉区間は指定した整数を含むかどうかを判定できる。また、別の閉区間と等価かどうかや、完全に含まれるかどうかも判定できる。

https://gist.github.com/twada/75fb219c8cc180e9de166d8a58e877b0

## TODO

- [x] 整数閉区間を示すクラス
  - [x] `constructor` は指定した整数の下端点と上端点を閉区間とした整数閉区間を返す
    - [x] 上端点と下端点が整数ではないときには、 `Error` を発生させる
      - [x] 下端点 `"string"` , 上端点 `{ object: true }` のときには、 `Error` を発生させる
      - [x] 下端点 `0.1` , 上端点 `5.5` のときには、 `Error` を発生させる
    - [x] 上端点より下端点が大きいときには、 `Error` を発生させる
      - [x] 下端点 `8` , 上端点 `3` のときには、 `Error` を発生させる
    - [x] そうでなければ下端点と上端点を保持するインスタンスを作成する
      - [x] 下端点 `3` , 上端点 `8` のときには、これを保持するインスタンスを作成する
  - [x] `toString` メソッドは、整数閉区間の文字列表現を返す
    - [x] 下端点 `3` , 上端点 `8` のときには、文字列表記 `[3, 8]` を返す
  - [x] `has` メソッドは指定した整数を含むかどうかを判定できる
    - [x] 整数閉区間に対して引数が範囲内であれば、 `true` を返す
      - [x] 下端点 `3` , 上端点 `8` の整数閉区間に対して引数が `3` のとき、 `true` を返す
      - [x] 下端点 `3` , 上端点 `8` の整数閉区間に対して引数が `5` のとき、 `true` を返す
      - [x] 下端点 `3` , 上端点 `8` の整数閉区間に対して引数が `8` のとき、 `true` を返す
    - [x] 整数閉区間に対して引数が範囲外であれば、 `false` を返す
      - [x] 下端点 `3` , 上端点 `8` の整数閉区間に対して引数が `2` のとき、 `false` を返す
      - [x] 下端点 `3` , 上端点 `8` の整数閉区間に対して引数が `9` のとき、 `false` を返す
  - [x] `isEquals` メソッドは、別の閉区間と等価かどうか判定できる
    - [x] 引数に `ClosedRange` クラスのインスタンス以外の値のとき、 `false` を返す
      - [x] 引数が `{ lowerEndpoint: 3, uppperEndpoint: 8 }` の `Object` のときには、 `false` を返す
    - [x] 下端点と上端点が一致しているとき、 `true` を返す
        - [x] 下端点 `3` , 上端点 `8` の整数閉区間に対して引数が下端点 `3` , 上端点 `8` の整数閉区間のとき、 `true` を返す
    - [x] そうでなければ `false` を返す
        - [x] ~下端点 `3` , 上端点 `8` の整数閉区間に対して引数が下端点 `4` , 上端点 `8` の整数閉区間のとき、 `false` を返す~
        - [x] ~下端点 `3` , 上端点 `8` の整数閉区間に対して引数が下端点 `3` , 上端点 `9` の整数閉区間のとき、 `false` を返す~
        - [x] 下端点 `3` , 上端点 `8` の整数閉区間に対して引数が下端点 `4` , 上端点 `9` の整数閉区間のとき、 `false` を返す
  - [x] `includes` メソッドは、別の閉区間に完全に含まれるかどうか判定できる
    - [x] 整数閉区間Aに対して整数閉区間Bが、Aの上端点よりもBの上端点の方が小さいか等価であり、Aの下端点よりもBの上端点の方が大きいか等価であるとき、 `true` を返す
      - [x] 下端点 `3` , 上端点 `8` の整数閉区間に対して引数が下端点 `3` , 上端点 `8` の整数閉区間のとき、 `true` を返す
      - [x] 下端点 `3` , 上端点 `8` の整数閉区間に対して引数が下端点 `4` , 上端点 `7` の整数閉区間のとき、 `true` を返す
    - [x] そうでなければ `false` を返す
      - [x] 下端点 `3` , 上端点 `8` の整数閉区間に対して引数が下端点 `2` , 上端点 `8` の整数閉区間のとき、 `false` を返す

**Comment by progfay** [comment]
![image](https://user-images.githubusercontent.com/19568747/78978209-57479600-7b54-11ea-9b80-e11d729da40f.png)
